### PR TITLE
Issue68 - Improve the quality of the Panel App API Functions script

### PR DESCRIPTION
**Pull request by PatrickWeller**
For #18 and Sprint 3 I've brought the panel app api functions up to a higher quality

1. Improved Error handling
2. PEP8 compliant according to pylint
image
4. In line commenting
5. Doc strings in Numpy format
6. Top level documentation in Numpy format
7. Logging added to key bits of commands, and errors. I know we said we wouldn't for accessories files, but this seems OK to me after considering it, very few logging lines will be run from these commands anyway.
8. Created tests with 100% pass rate:
image
9. Created tests with 100% coverage for panel_app_api_functions.py according to "coverage report -m"
image

I also added an additional function that will contribute towards #52 #57 (Duplicate issue) to be able to compare gene lists for user story #56 . The function is:
- get_response_old_panel_version which uses a different API end point to get old versions of a panel

The above required using the database primary key for the panel, rather than the R number, so this was also added as an output of get_genes 

Creation of a logger is temporarily in this file to be removed once I tackle loggers more fully. 
README.md not added to. Not sure if it will need to go in there at all, but for now waiting for Ash to redo the README.

### CODE REVIEW

**Comment by madysonic** [comment]
Documentation looks good, and good amount of tests implemented. Tests all pass on my machine too. As discussed, you have added the time out variable to api requests, but we need to add additional handling for when it times out and write tests for this. 

Also, do you think it is likely we will need to use panel_pk instead of panel_id (R number) for more than just comparing gene lists? If so we may need a function in the future to easily convert between the two. Just a thought.

**Comment by PatrickWeller** [comment]
All changes made as requested

**Comment by ASendellPrice** [comment]
Hi Patrick, when running unit tests on my machine I ran into the following failed test:
image
Can you fix please :)

**Comment by PatrickWeller** [comment]
@ASendellPrice Sorry about that Ash, corrected that. Sorry, changed some messages when making pylint compliant.

**Comment by ASendellPrice** [comment]
Thanks for resolving that issue @PatrickWeller. All unit tests were able to run on my machine. Happy for branch to be merged.

**Pull request merged**
