### PR TITLE
Issue24 and Issue18: check if bed file exists and compare bed files

### PR DESCRIPTION
**Pull request by madysonic**
### Summary
#24 and #18 for Sprint 4.

### Files Created:
* PanelPal/compare_bedfiles.py - main function to compare the contents of two bed files. It takes 2 file paths as input and outputs a comparison file containing the differences.
* test/test_compare_bedfiles.py - tests for compare_bedfiles.py
* PanelPal/accessories/bedfile_functions.py - actual functions called in the above script and also now in generate_bed.
* test/test_bedfile_functions.py - test for bedfile_functions.py

### Files Updated:
* PanelPal/generate_bed.py - updated to include logic to check if a bed file already exists, using one of the new functions from bedfile_functions.py. Also added logic to check panel_id is in the correct format after I ran into a bug.
* test/test_generate_bed.py - tests for the added logic described above.
* Also minor change in PanelPal/accessories/variant_validator_api_functions.py - I added the word "exon" to the concatenated file name as I think this makes it clearer.

No new dependencies.

### Pylint is happy with new files:
image
image

### Testing
All tests pass without error.
image

image

image

Coverage for new files:

image

image

### Notes

Note, as always, file paths and module import paths are all over the place with my VS Code, so please check things run properly on yours. 

Next steps will be adding the compare_bedfiles.py function to the package :)

### CODE REVIEW

**Comment by madysonic** [comment]
GitHub's automated tests have failed due to my import module paths mentioned above. I'll try changing these and see if it runs on github, but  they will fail for me locally then.

**Comment by madysonic** [comment]
Finally got GitHub Workflow to run my tests!

It was an issue with file paths and the working directory that GitHub uses, and because some of my tests actually execute the script from command line (I didn't want to just mock them all, as I felt like that wasn't testing the real-world functionality). 

I needed to capture the current working directory and set this as the working directory in the environment variable every time each time it executes a command (i.e., within the subprocess.run parts of each of these tests).

**Comment by ASendellPrice** [comment]
I tried tested the code using R83 version 1 and 8 (current version). The resulting file only contains the file header:
image
image

However, I was expecting to see some content in this file as 290 genes have been added since version 1:
image
image

Can you look into this please?

**Comment by madysonic** [comment]
Issue due to generate_bed only generating the most recent version of panel - so specify v1 vs v8 produced identical files. Fixed as discussed in our catch-up.

**Comment by ASendellPrice** [comment]
Updated code reviewed. compare_bedfiled.py successfully creates output (see screenshot). Will now merge to development branch.
image

**Pull request merged**
