### PR TITLE
Database - issue #35

### PR DESCRIPTION
**Pull request by RVel37**

### CODE REVIEW

**Comment by PatrickWeller** [comment]
More comments would make the code a lot more readable, thanks :)

**Comment by PatrickWeller** [comment]
@RVel37 the old file api_query.py has reappeared in this, please remove. Thanks

**Comment by RVel37** [comment]
@PatrickWeller All done

**Comment by RVel37** [comment]
Fixed merge conflicts, can someone please push it into development?

**Comment by madysonic** [comment]
Can we remove the pycache files please? :) then looks good to merge!

**Pull request merged**
